--- #prod
spring:
  profiles:
    active: prod

  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://127.0.0.1:3306/eatthis?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root1234
      hikari:
        poolName: Hikari
        maximum-pool-size: 10
        max-lifetime: 1800000
        auto-commit: false
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048

logging:
  level:
    org.springframework.web: info
    co.kr.heeseong: info
    jdbc.sqlonly : off
    jdbc.sqltiming : off
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.resultsettable : off
    jdbc.connection: off
  file:
    name: ${file.separator}/u00${file.separator}www_contents${file.separator}logs${file.separator}eatthis${file.separator}eatthis.log
  logback:
    rollingpolicy:
      max-history: 90
      max-file-size: 10MB

default-upload-path: ${file.separator}u00${file.separator}www_contents${file.separator}upload