server:
  port: 8080

spring:
  profiles:
    active: local

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    suffix: .html

#DB configuration
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - mapper/*.xml
  type-aliases-package: com.heeseong.util.model

--- #local
spring:
  profiles: local
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/eatthis?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&verifyServerCertificate=false&useSSL=false
    username: root
    password: 1234
    hikari:
      poolName: Hikari
      maximum-pool-size: 10
      max-lifetime: 1800000
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql : true
      ddl-auto: none

logging:
  level:
    org.springframework.web: info
    com.heeseong: info
    jdbc.sqlonly : off
    jdbc.sqltiming : off
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.resultsettable : off
    jdbc.connection: off
file:
  path: D:${file.separator}log${file.separator}

default-upload-path: D:${file.separator}upload${file.separator}

--- #dev

--- #prod